### ISSUE TITLE
Allocations specs

### ISSUE THREAD

**Issue by jayalaves** [AutarkLabs/autark-design#22]

**Comment by jayalaves** [comment]
Pending some product specs.

**Comment by stellarmagnet** [comment]
Here are the high-level specs for Allocations, and some things that need to be thought through. @jayalaves - can you flesh them out and think of the different edge cases? If you want to take a stab at refining the written text as well and figuring out the best place to document it for the dev team (product specs in notion), that would be a good step toward end-to-end product design.

* Accounts should not be able to “hold” ETH or any token, instead we implement a system that is more related to budgeting
* The way that account budgeting works is each account is tied to a single token (although you can have multiple accounts that also are tied to that token).
* Ideally, accounts should be able to budget for ETH and send ETH (from the vault)
* Some thing we need to think through is the concept of budget periods:
    * The way the Finance app works is that the budgeting period is set during app initialization, and this period is applied to all of your token budgets.
        * Do we want a global budgeting period for Allocations, or should you be able to choose the budgeting period on an account by account basis?


New Account panel:
* Account Name
* Account Token
* Budget Amount
* Budget Period (if we don’t have this as a global setting)
    * monthly, weekly, etc


Landing page, account card:
* Budget / Budget Period  (e.g. 10 DAI / month)
* Amount spent for the current period / amount remaining for the current period

Use cases:
* How does an account card look if you’ve used up the budget for the current period?

@Quazia - please give this a once over today and comment on the technical viability of the spec.

**Comment by jayalaves** [comment]
I've started to expand these specs on Notion under [Product Specs](https://www.notion.so/autark/Allocations-06a3914a68774139899d2bc0019c02e0). I've still got some details to think about, and will have some initial sketches tomorrow most likely.

**Comment by jayalaves** [comment]
Extended specs and added several questions for review before we can move forward with low fidelity designs to start envisioning the layout.
