### ISSUE TITLE
Quasi-transferable token whitelisting design shape up

### ISSUE THREAD

**Issue by jayalaves** [AutarkLabs/autark-design#25]
Concept design for a whitelist within the Token Manager app to allow admins to transfer non-transferable tokens under specific circumstances.

**Comment by jayalaves** [comment]
@stellarmagnet Would it be possible to facilitate this functionality as part of the Permissions, rather than on the app itself? For example:

**1 -** Go to Permissions and add permission within the Voting app. Here, the option that may be missing is to grant this permission to a list of addresses, if the use case of quasi-transferability is tied to multiple accounts having that permission enabled.

<img width="449" alt="Screenshot 2019-07-09 at 10 41 24" src="https://user-images.githubusercontent.com/28843778/60873237-53d65580-a236-11e9-8a9a-a3f5fce4d03e.png">

**2 -** When choosing the option, we could create an option called "Quasi-transferability" or "Transfer non-transferable tokens", which overrides the non-transferability of the token for a specific list of addresses.

<img width="423" alt="Screenshot 2019-07-09 at 10 41 36" src="https://user-images.githubusercontent.com/28843778/60873451-b7f91980-a236-11e9-9056-64b4afc28265.png">

Does this logic make sense?

**Comment by jayalaves** [comment]
Unable to have it reviewed within this sprint, so I'm moving it to the current one.

**Comment by stellarmagnet** [comment]
Is the quasi-transferable token spec utilizing the ACL to manage the token transfer permission, @Quazia ?

**Comment by jayalaves** [comment]
Just received specs from Arthur. Permission to edit the whitelist should be within Permissions, but adding and removing accounts for token whitelisting should ideally happen within the Token Manager app. Bringing this back to 'In Progress' to shape up the task and execute.
