### ISSUE TITLE
Aragon Network Organization badge

### ISSUE THREAD

**Issue by jayalaves** [AutarkLabs/autark-design#32]
- [x] Take the [dark monochrome](https://wiki.aragon.org/design/artwork/Governed_By/Governed_By_Dark_Monochrome.svg) and edit on Photoshop as reviewed during our design sync call.
 
Figma file [available here](https://www.figma.com/file/HD7Sk1XKCg1gN3KIYNTJrjRS/Aragon-Website-Badge?node-id=0%3A1).

**Comment by jayalaves** [comment]
[Finished initial exploration](https://www.figma.com/file/by4jTfmxgL3bUmn1KmZPq3sb/Aragon-Website-Badge?node-id=0%3A1). I will introduce this into the design sync with Yalda today to speed up the internal iterations, if any, before sharing with the Flock community.

**Comment by jayalaves** [comment]
Need to fix readability issues and reupload

**Comment by jayalaves** [comment]
Improved the readability considerably by fixing the text proportions. Which color variation do you like better?

<img width="1440" alt="Screenshot 2019-07-17 at 14 38 52" src="https://user-images.githubusercontent.com/28843778/61376149-e0b98880-a8a0-11e9-8467-bbc6ec676833.png">
<img width="1440" alt="Screenshot 2019-07-17 at 14 39 35" src="https://user-images.githubusercontent.com/28843778/61376150-e0b98880-a8a0-11e9-98c4-8cfb67396bd9.png">

**Comment by stellarmagnet** [comment]
I like the white one...

I feel like there may be more space below "network organization" than above "Aragon"? but not sure.

I'd also reduce the size of this badge by 80% so it doesn't dominate as much, and make sure we can still read it

**Comment by jayalaves** [comment]
> I feel like there may be more space below "network organization" than above "Aragon"? but not sure.

Yes, depends if you consider the space from the baseline or from the 'g' descender line. I've tweaked it so that we now consider the baseline, which should balance the space out more.

> I'd also reduce the size of this badge by 80% so it doesn't dominate as much, and make sure we can still read it... and increase the autark logo by 120%

✅
