### ISSUE TITLE
Upgrade Dot Voting UI

### ISSUE THREAD

**Issue by jayalaves** [AutarkLabs/autark-design#34]
Integrating Aragon's new design system and our contextual discussions onto a new upgraded version of the Dot Voting app, including responsive views.

Figma file: [available here](https://www.figma.com/file/NZQk49jsqKMHdWxsEwSxJs5n/Dot-Voting?node-id=61%3A115)

Screens:
- [x] Placeholder
- [x] Main View
- [x] Vote Main View
- [x] Voting Views with slider variations
- [x] Voted View
- [x] Comments process

For future release:
- [x] Filtered views
- [x] New dot vote process

Resolutions:
- [x] MacBook (1152x700)
- [x] MacBook Pro (1440x900)
- [x] iPad Mini 9.7" (768x1024)
- [x] iPhone SE (320x568)
- [x] iPhone X (375x812)

Changes:
- [x] Adopt the new tabs system
- [x] Design a cancel mode within a voting view

Others:
- [x] Create a new issue for a collection of future release updates
- [x] Create a new issue with master branch edits

**Comment by jayalaves** [comment]
Awaiting more information on the design system advancements from Aragon One.

**Comment by jayalaves** [comment]
Do we need labels like in the Voting specs from Aragon One?

**Comment by stellarmagnet** [comment]
> Do we need labels like in the Voting specs from Aragon One?

Yeah, we should just go with their design pattern for now. If we feel like the labels should be removed, we can address it in a future release.

**Comment by stellarmagnet** [comment]
To dos:

1) Move the "Created By" to be in the same location
2) Add the discussion/commenting designs to the Dot Voting mockups
